### ISSUE TITLE
碎文件命名按ascii来太麻烦了,建议按字符来,脚本内处理

### ISSUE THREAD

**Issue by skyblue** [justbilt/convert2fnt#1]

**Comment by justbilt** [comment]
按字符来确实比较简单,但是有些字符是无法作为文件名的,如`hhh_#.png`, `hhh_,.png`, 可以改进为同时使用.

`hhh_[0~9].png`
`hhh_[a~z].png`
`hhh_[A~Z].png`
这几个使用字符,其他的都用ascii来,但感觉还是不爽.
