### ISSUE TITLE
希望能能加入对汉字的支持

### ISSUE THREAD

**Issue by summerfish** [justbilt/convert2fnt#4]
目前这个工具各方面挺好用的，就是只支持英文和数字，如果用单个汉字的asic码好像就解析不出来了，希望能支持下汉字。

**Comment by justbilt** [comment]
这个工具正在计划用 Electron 重写, 目前基本上已经完成了. 但是 Windows 上打包有一些问题, 所以新版只有目前只有 Mac 版.

如果你恰好用的 Mac 的话, 可以在 Release 界面或者[这里][1]下载新版工具, 如果是 Windows 的话, 那么需要稍等几天, 我这几天搞一下, 应该很快可以出一个版本.

[1]: http://7xnfpc.com1.z0.glb.clouddn.com/convert2fnt-0.0.1-mac.zip

**Comment by summerfish** [comment]
嗯，十分感谢，辛苦了。我正好用的mac，所以下载了新版的工具试用了一下，感觉不错。就是遇到一些小问题，希望能帮忙查看下。我用这套数字图片，导出后发现"."这个符号在cocos studio里面怎么也显示不出来(这个符号在工具里用的字符是".")，能否帮我看下呢。资源在这里：链接: https://pan.baidu.com/s/1i56A8Wt 密码: 6iyf
还有一个小的建议：能否加一个一键清除列表的按钮呢，因为做完一套数字后，想做下一套数字，还需要把之前的数字一个一个点击删除，如果能一键清空数字列表是不是更好点呢。^_^

**Comment by justbilt** [comment]
> 导出后发现"."这个符号在cocos studio里面怎么也显示不出来

`dian.png`这张图片不知道你在工具中的字符输入栏输入的是什么 ? 默认的话应该是 `dian`, 这个是不对的, 你需要手动改为 `.`. 我尝试了一下, 是 OK 的.

> 能否加一个一键清除列表的按钮呢

这是一个很好的建议, 实现起来也很简单, 国庆期间我搞一下, 国庆后会更新一版.

谢谢你的使用和反馈.

**Comment by summerfish** [comment]
嗯，感谢回复。我这边测试还是没法显示出来"."，不知道是不是cocos studio的问题，我把测试工程发给你，你看下，我是在mac下，cocos studio 3.10，Xcode 9.0测试。
工程：链接: https://pan.baidu.com/s/1bAC1xO 密码: s4pf
数字字符设置:
![1](https://user-images.githubusercontent.com/8478223/31042302-469d30da-a5d7-11e7-89d9-31373ee81d97.png)
<img width="400" alt="2" src="https://user-images.githubusercontent.com/8478223/31042301-469a316e-a5d7-11e7-9a26-fcccbb8a53ec.png">

**Comment by justbilt** [comment]
经过尝试, 这个确实是一个 bug, 多次拖入文件会导致字符 id 错误. 目前你比较简单的解决方案是一次性拖入该字体所有的字符图片, 每打一个字体文件, 退出一下工具.

我会尽快修复这个bug.

**Comment by justbilt** [comment]
已经修复了这个问题, 您可以在 [Release Page](https://github.com/justbilt/convert2fnt/releases) 下载 0.0.2 版本.
